version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production
      API: http://192.168.1.12:3000/api
    restart: unless-stopped
    volumes:
      - .:/app